name: vcpkg
# build and test of tesseract on windows using vcpkg and cmake.
# vcpkg with -head does not work. https://github.com/microsoft/vcpkg/issues/16019
on:
  #push:
  #schedule:
  #  - cron: 0 23 * * *
  workflow_dispatch:
  
jobs:
  build_and_test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config: [Release]
        
    steps:
      - name: Setup Vcpkg and Integrate
        run: |
          git clone https://github.com/microsoft/vcpkg
          vcpkg/bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=.\vcpkg" >> $ENV:GITHUB_ENV
          vcpkg/vcpkg integrate install

      - name: Install Leptonica and Image Libraries using Vcpkg
        run: |
          vcpkg/vcpkg install leptonica:x64-windows

      - name: Checkout, Configure and Build Tesseract
        run: |
          git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git
          cd tesseract             
          git submodule sync --recursive        
          # cmake . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF "-DCMAKE_TOOLCHAIN_FILE=${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
          cmake . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config ${{ matrix.config }}

      - name: Create and Configure CMakeLists for basicapitest
        run: |
          echo ${{github.workspace}}
          cd tesseract/test
          cat << "EOF" > CMakeLists.txt
          cmake_minimum_required(VERSION 3.19)
          project(basicapitest)
          find_package(Tesseract REQUIRED)
          find_package(Leptonica REQUIRED)
          include_directories(${Tesseract_INCLUDE_DIRS})
          include_directories(${Leptonica_INCLUDE_DIRS})
          add_executable(basicapitest testing/basicapitest.cpp)
          target_link_libraries(basicapitest ${Leptonica_LIBRARIES})
          target_link_libraries(basicapitest Tesseract::libtesseract)
          add_library(libtesseract UNKNOWN IMPORTED)
          set_property(TARGET libtesseract PROPERTY IMPORTED_LOCATION ${{github.workspace}}/build/Release/tesseract50.lib)
          target_link_libraries(basicapitest Tesseract::libtesseract)
          EOF

      - name: Build basicapitest
        run: |
          cd tesseract/test
          # cd test
          cmake . "-DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake --build . --config ${{ matrix.config }}

      - name: Download tessdata and image files used for tests
        run: |
          git clone https://github.com/egorpugin/tessdata tessdata_unittest
          mv tessdata_unittest/* ../

      - name: Run basicapitest
        run: |
          cd tesseract/test
          # cd test
          ${{github.workspace}}\build\Release\basicapitest.exe

      - name: Run Tesseract CLI on test images in different languages
        run: |
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\phototest.tif - --oem 1  --tessdata-dir ..\tessdata
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\raaj.tif - -l hin --oem 1   --tessdata-dir ..\tessdata
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\viet.tif - -l vie --oem 1   --tessdata-dir ..\tessdata
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\hebrew.png - -l heb --oem 1   --tessdata-dir ..\tessdata
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\eurotext.tif - -l fra --oem 1 --psm 6  --tessdata-dir ..\tessdata_best
          ${{github.workspace}}\build\Release\tesseract.exe  test\testing\arabic.tif - -l ara --oem 1 --psm 6  --tessdata-dir ..\tessdata

      - name: List languages in different test tessdata-dirs
        run: |
          ${{github.workspace}}\build\Release\tesseract.exe  --list-langs --tessdata-dir ../tessdata
          ${{github.workspace}}\build\Release\tesseract.exe  --list-langs --tessdata-dir ../tessdata_best
          ${{github.workspace}}\build\Release\tesseract.exe  --list-langs --tessdata-dir ../tessdata_fast
